export const SET_USERS = "SET_USERS";
export const SET_SELECTED_DEPARTMENT = "SET_SELECTED_DEPARTMENT";
export const SET_DEPARTMENTS = "SET_DEPARTMENTS";
export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
export const SET_SORT_OPTION = "SET_SORT_OPTION";